"""alter table User (followers field)

Revision ID: 1525e2399b18
Revises: 506467cdb3b8
Create Date: 2025-07-28 12:46:53.610964

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1525e2399b18'
down_revision = '506467cdb3b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###