"""alter table User (followers field)

Revision ID: 506467cdb3b8
Revises: 0ded03c43357
Create Date: 2025-07-28 12:45:57.943068

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '506467cdb3b8'
down_revision = '0ded03c43357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###